[package]
name = "libarchive_sys"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
libc = "0.2.137"
lzma-sys = "0.1.20"
bzip2-sys = "0.1.11+1.0.8"
libz-sys = "1.1.8"
zstd-sys = "2.0.4+zstd.1.5.2"

[build-dependencies]
bindgen = "0.63.0"
cmake = "0.1.49"
