name: CI Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  style_check:
    runs-on: ubuntu-latest
    steps:
      - uses: dtolnay/rust-toolchain@beta
        with:
          components: clippy, rustfmt
      - run: npm install -g zx
      - uses: actions/checkout@v3
      - run: ./scripts/ci.mjs style-check
  test:
    strategy:
      matrix:
        os: [
          macos-latest, ubuntu-latest, windows-latest
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: dtolnay/rust-toolchain@beta
      - run: npm install -g zx
      - uses: actions/checkout@v3
      - run: zx ./scripts/ci.mjs test
