name: CI Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  style_check:
    runs-on: ubuntu-latest
    steps:
      - run: vcpkg install libarchive
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: beta
          override: true
          components: rustfmt, clippy
      - uses: actions/checkout@v3
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all-targets -- -D warnings
  test:
    continue-on-error: true
    strategy:
      matrix:
        os: [
          macos-latest, ubuntu-latest, windows-latest
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - run: vcpkg install libarchive
      - uses: actions/checkout@v3
      - run: cargo test --release
